"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { ResellModal } from "./ResellModal";

interface ReportViewerProps {
  memoId: string;
  title: string;
  content: string;
  generatedAt: string;
  originalPrice: number;
  resaleEnabled: boolean;
}

export function ReportViewer({
  memoId,
  title,
  content,
  generatedAt,
  originalPrice,
  resaleEnabled,
}: ReportViewerProps) {
  const [showResellModal, setShowResellModal] = useState(false);

  const date = new Date(generatedAt).toLocaleDateString("ja-JP", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="relative max-w-3xl mx-auto">
      {/* Watermark */}
      <div
        className="absolute inset-0 flex items-center justify-center pointer-events-none select-none overflow-hidden"
        style={{ zIndex: 0 }}
      >
        <span
          className="text-[#1a1a1a]/5 font-serif text-4xl font-bold whitespace-nowrap"
          style={{ transform: "rotate(-30deg)", letterSpacing: "0.3em" }}
        >
          ALPHA MEMO PROTOCOL
        </span>
      </div>

      <div className="relative" style={{ zIndex: 1 }}>
        {/* Header */}
        <div className="border-b-2 border-[#1a1a1a] pb-4 mb-6">
          <p className="text-xs font-mono uppercase tracking-widest text-[#c8a96e] mb-2">
            Alpha Research Report · {date}
          </p>
          <h1 className="font-serif text-2xl text-[#1a1a1a] leading-tight">{title}</h1>
        </div>

        {/* Content */}
        <div className="prose prose-sm max-w-none report-content">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
        </div>

        {/* Footer */}
        <div className="border-t border-[#1a1a1a]/20 mt-8 pt-4">
          <p className="text-xs font-mono text-[#1a1a1a]/40">
            Generated by Alpha Memo Protocol · x402 Payment Protocol ·{" "}
            {new Date(generatedAt).toISOString()}
          </p>
        </div>

        {/* Resell section */}
        {resaleEnabled && (
          <div className="mt-6 border border-[#c8a96e]/40 bg-[#c8a96e]/5 p-4">
            <p className="text-sm font-mono text-[#1a1a1a]/70 mb-3">
              このレポートは転売可能です。販売額の20%がプロトコルへ還元されます。
            </p>
            <button
              onClick={() => setShowResellModal(true)}
              className="px-6 py-2 border border-[#c8a96e] text-[#c8a96e] font-mono text-sm uppercase tracking-widest hover:bg-[#c8a96e] hover:text-[#1a1a1a] transition-colors"
            >
              このレポートを転売する
            </button>
          </div>
        )}
      </div>

      {showResellModal && (
        <ResellModal
          memoId={memoId}
          minPrice={originalPrice + 0.5}
          onClose={() => setShowResellModal(false)}
        />
      )}
    </div>
  );
}
